/******************************************************************************
 *
 * Module: HC-SR04 Ultrasonic sensor
 *
 * File Name: HC-SR04.c
 *
 * Description: Source file for the HC-SR04 driver
 *
 * Author: Omar Talaat
 *
 *******************************************************************************/

#include "HC-SR04.h"
#include "icu.h"
#include "gpio.h"
#include "common_macros.h" /* To use the macros like SET_BIT */
#include <util/delay.h>

/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/

volatile static uint8 g_count=0;

/*******************************************************************************
 *                      Functions Definitions                                   *
 *******************************************************************************/

/*
 * Description :
 * Initialize the Ultrasonic
 * Initialize the ICU driver as required.
 * Setup the ICU call back function.
 * Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void)
{
	ICU_ConfigType ICU_Configurations={F_CPU_8,RAISING};
	ICU_init(&ICU_Configurations);
	ICU_setCallBack(Ultrasonic_edgeProcessing);
	GPIO_setupPinDirection(PORTB_ID,PIN5_ID,PIN_OUTPUT);
}

/*
 * Description :
 * Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void)
{
	GPIO_writePin(PORTB_ID,PIN5_ID,LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(PORTB_ID,PIN5_ID,LOGIC_LOW);
}


/*
 * Description :
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void)
{
	ICU_setEdgeDetectionType(RAISING);
	Ultrasonic_Trigger();
	while(g_count!=2);
	g_count=0;
	return 1+(ICU_getInputCaptureValue()/58);
}


/*
 * Description :
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void)
{
	if(g_count==0)
	{
		ICU_setEdgeDetectionType(FALLING);
		ICU_clearTimerValue();
	}


	g_count++;

}
